version: '3.1'

services:
    front_ssr:
        container_name: front_ssr
        build:
            context: './'
            dockerfile: './docker/Dockerfile.dev'
        volumes:
            - '.:/srv/front:rw,cached'
            - '/srv/front/node_modules'
        ports:
            - 3000:3000