version: '3.1'

services:
    front_ssr_fr:
        container_name: front_ssr_fr
        build:
            context: './docker'
            dockerfile: './Dockerfile'
        volumes:
            - '.:/srv/front:rw,cached'
        ports:
            - 3000:3000
        command: npm run ${NEXT_START_CMD}
