apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  selector: 
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: front-container
          image: mo29172/unionista_front:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom: 
                secretKeyRef:
                  name: front-envs
                  key: NEXT_PUBLIC_API_BASE_URL
            