name: Deployment front (PREPROD)

on:
    push:
        branches: [dev]

jobs:
    remove:
        runs-on: ubuntu-latest
        environment: preprod
        steps:
            - name: remove existing folder front
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.REMOTE_PASSWORD }}
                  port: ${{ secrets.REMOTE_PORT }}
                  script: '[ ! -e /srv/front/* ] || rm -r /srv/front/*'

    build:
        runs-on: ubuntu-latest
        environment: preprod
        needs: remove
        steps:
            - name: Download project from git
              uses: actions/checkout@v2

            - name: npm install
              run: npm i

            - name: Build project
              run: npm run build

    deploy:
        runs-on: ubuntu-latest
        environment: preprod
        needs: build

        steps:
            - name: Download project from git
              uses: actions/checkout@v2

            - name: Export environment variables
              run: |
                  echo NEXT_START_CMD="$NEXT_START_CMD" >> ./.env
              env:
                  NEXT_START_CMD: '${{ secrets.NEXT_START_CMD }}'

            - name: copy .env file via ssh
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_SSH_KEY }}
                  # password: ${{ secrets.PREPROD_PASSWORD }}
                  source: '.env'
                  target: '/srv/front/source'
            # - name: Set up SSH
            #   run: |
            #       mkdir -p ~/.ssh/
            #       echo "$PREPROD_SSH_KEY" > ./deploy.key
            #       sudo chmod 600 ./deploy.key
            #       echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            #   shell: bash
            #   env:
            #       PREPROD_SSH_KEY: ${{secrets.PREPROD_SSH_KEY}}
            #       SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
            - name: Set up deploy.key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$REMOTE_SSH_KEY" > ./deploy.key
                  sudo chmod 600 ./deploy.key
                  # echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                  REMOTE_SSH_KEY: ${{secrets.REMOTE_SSH_KEY}}
                  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

            - name: Install PM2
              run: npm i pm2 --force

            - name: Deploy
              run: |
                  npm run deploy-preprod

    # restart_pm2:
    #     runs-on: ubuntu-latest
    #     environment: preprod
    #     needs: deploy
    #     steps:
    #         - name: launch SSR server
    #           uses: appleboy/ssh-action@master
    #           with:
    #               host: ${{ secrets.REMOTE_HOST }}
    #               username: ${{ secrets.REMOTE_USER }}
    #               key: ${{ secrets.REMOTE_SSH_KEY }}
    #               port: ${{ secrets.REMOTE_PORT }}
    #               script: 'pm2 restart front'
