name: Deployment front (PREPROD)

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: preprod
        steps:
            - name: Download project from git
              uses: actions/checkout@v2

            - name: npm install
              run: npm i

            - name: Build project
              run: npm run build

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: build docker image
              run: docker build -t mo29172/unionista_front:v${{ github.run_number }} -f ./docker/Dockerfile ./

            
            - name: push image to docker hub
              run: |
                docker push mo29172/unionista_front:v${{ github.run_number }}
            
            - name: update front deployment file version
              run: |
                sed -i -e"s/:latest/:v${{ github.run_number }}/" docker/k8s/front-deployment.yaml

            - name: copy k8s files via ssh
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.REMOTE_SSH_KEY }}
                source: 'docker/k8s/front-deployment.yaml,docker/k8s/front-cluster-ip-service.yaml,docker/k8s/front-ingress-service.yaml'
                target: '/srv/k8s/front'
                strip_components: 2

            - name: apply k8s files
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.SSH_SECOND_USER }}
                password: ${{ secrets.REMOTE_PASSWORD }}
                script: |
                  kubectl apply -f /srv/k8s/front
    
    # - name: copy .next directory with SSH
    #   uses: easingthemes/ssh-deploy@v2.1.4
    #   env:
    #       SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
    #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #       SOURCE: '.next'
    #       TARGET: '/srv/front/source'

    # deploy:
    #     runs-on: ubuntu-latest
    #     environment: preprod
    #     needs: build

    #     steps:
    #         - name: Download project from git
    #           uses: actions/checkout@v2

    #         - name: Export environment variables
    #           run: |
    #               echo NEXT_START_CMD="$NEXT_START_CMD" >> ./.env
    #           env:
    #               NEXT_START_CMD: '${{ secrets.NEXT_START_CMD }}'

    #         - name: copy .env file via ssh
    #           uses: appleboy/scp-action@master
    #           with:
    #               host: ${{ secrets.REMOTE_HOST }}
    #               username: ${{ secrets.REMOTE_USER }}
    #               key: ${{ secrets.REMOTE_SSH_KEY }}
    #               source: '.env'
    #               target: '/srv/front/source'
            # - name: copy .next file via ssh
            #   uses: appleboy/scp-action@master
            #   with:
            #       host: ${{ secrets.REMOTE_HOST }}
            #       username: ${{ secrets.REMOTE_USER }}
            #       key: ${{ secrets.REMOTE_SSH_KEY }}
            #       source: '.next'
            #       target: '/srv/front/source'

            # - name: Set up SSH
            #   run: |
            #       mkdir -p ~/.ssh/
            #       echo "$PREPROD_SSH_KEY" > ./deploy.key
            #       sudo chmod 600 ./deploy.key
            #       echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            #   shell: bash
            #   env:
            #       PREPROD_SSH_KEY: ${{secrets.PREPROD_SSH_KEY}}
            #       SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
            # - name: Set up deploy.key
            #   run: |
            #       mkdir -p ~/.ssh/
            #       echo "$REMOTE_SSH_KEY" > ./deploy.key
            #       sudo chmod 600 ./deploy.key
            #       echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            #   shell: bash
            #   env:
            #       REMOTE_SSH_KEY: ${{secrets.REMOTE_SSH_KEY}}
            #       SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

            # - name: Install PM2
            #   run: npm i pm2 --force

            # - name: Deploy
            #   run: |
            #       npm run deploy-preprod

    # restart_pm2:
    #     runs-on: ubuntu-latest
    #     environment: preprod
    #     needs: deploy
    #     steps:
    #         - name: launch SSR server
    #           uses: appleboy/ssh-action@master
    #           with:
    #               host: ${{ secrets.REMOTE_HOST }}
    #               username: ${{ secrets.REMOTE_USER }}
    #               key: ${{ secrets.REMOTE_SSH_KEY }}
    #               port: ${{ secrets.REMOTE_PORT }}
    #               script: 'pm2 restart front'
